// Auto-generated by scripts/generate-env.ps1. Do not commit this file.
window.__ENV__ = {
  FIREBASE_API_KEY: 'AIzaSyBOPF6IE9bTT6rHn5a2GklEO8XXJUrv-VY',
  FIREBASE_AUTH_DOMAIN: 'extraiut.firebaseapp.com',
  FIREBASE_PROJECT_ID: 'extraiut',
  FIREBASE_STORAGE_BUCKET: 'extraiut.firebasestorage.app',
  FIREBASE_MESSAGING_SENDER_ID: '993609489576',
  FIREBASE_APP_ID: '1:993609489576:web:58b90f5df065a98eb4769d'
};
